// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250425112458_Teste4")]
    partial class Teste4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entity.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1990, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ana Silva teste2"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1985, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Bruno Souza"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1992, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Carla Pereira teste2"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1988, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Diego Costa"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1991, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Eduarda Lima"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1983, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernando Rocha"
                        },
                        new
                        {
                            Id = 7,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1994, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gabriela Mendes"
                        },
                        new
                        {
                            Id = 8,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1989, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Henrique Alves"
                        },
                        new
                        {
                            Id = 9,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1995, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Isabelly Gomes"
                        },
                        new
                        {
                            Id = 10,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1986, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "João Pedro"
                        },
                        new
                        {
                            Id = 11,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1993, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Karina Teixeira"
                        },
                        new
                        {
                            Id = 12,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1987, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Lucas Vieira"
                        },
                        new
                        {
                            Id = 13,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1996, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Mariana Cruz"
                        },
                        new
                        {
                            Id = 14,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1984, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Nathan Ribeiro"
                        },
                        new
                        {
                            Id = 15,
                            DataCriacao = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1997, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Olivia Barros"
                        });
                });

            modelBuilder.Entity("Core.Entity.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("Core.Entity.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("INT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<int>("LivroId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LivroId");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("Core.Entity.Pedido", b =>
                {
                    b.HasOne("Core.Entity.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entity.Livro", "Livro")
                        .WithMany("Pedidos")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Core.Entity.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Core.Entity.Livro", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
